version: "3.1"

services:
  gallery:
    build: ./docker/database
    container_name: gallery_db
    environment:
      POSTGRES_MULTIPLE_DATABASES: gallery,gallery_test
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding UTF8 --lc-collate ru_RU.UTF-8 --lc-ctype ru_RU.UTF-8 --lc-messages en_US.UTF-8'
    volumes:
      - ./docker/database/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 6432:5432